# Generated by Django 3.0.2 on 2020-01-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20200124_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=10000),
        ),
    ]
